### ISSUE TITLE
Sticky touches on desktop

### ISSUE THREAD

**Issue by austegard** [ais-open/touchview#2]
If you click an image and drag, the touch-up (dragend?) event does not appear to fire, leaving the visible touch on the screen

**Comment by iangilman** [comment]
I've done two things to mitigate this now: whenever a browser level drag event starts, we cancel the visible touch, and next time you click, if there's a visible touch still lingering around, we kill it. I believe this is as good as we can do... there doesn't seem to be a way to ride along on the drag itself. At any rate, no more sticky touches.
