### ISSUE TITLE
I need more color

### ISSUE THREAD

**Issue by AppliedIS** [ais-open/touchview#4]
While nice and clean, the current result is a bit austere, and you can't tell two touches apart.  I would like to see a different hue associated with each touch

**Comment by iangilman** [comment]
I suspect this would limit the appeal of the bookmarklet. Every video I've ever seen of an iPad interface that uses some sort of touch display just sticks with the plain white, or at the very least always the same color. A rainbow of touch dots is just going to distract from the content people are trying to show off, and probably clash with their UI. I recommend we don't do this.

**Comment by AppliedIS** [comment]
Could we make the ring a bit more obvious at least?

**Comment by iangilman** [comment]
Yes, that sounds good.

**Comment by iangilman** [comment]
Ok, the black border is now 2px wide... how's that?

**Comment by iangilman** [comment]
Good enough, I suppose; closing.
