### ISSUE TITLE
Touch size should take zoom factor into account

### ISSUE THREAD

**Issue by AppliedIS** [ais-open/touchview#5]
Sadly our github-online-editor-created TouchView page is not using a responsive design, and so to read it on a phone you have to zoom in and out.  It would make sense for the touch circles to adjust in size based on the current zoom factor to maintain more parity between the user's finger and the visual touch circle.  When zoomed out, currently the circles are tiny.

**Comment by iangilman** [comment]
That would be awesome, though I'm not sure if we have access to the zoom factor... you figure there must be at least some hack somewhere.

**Comment by iangilman** [comment]
I haven't been able to find anything. There are some suggestions here: 

http://stackoverflow.com/questions/668462/safari-iphone-how-to-detect-zoom-level-and-offset

... but they're all dead ends. 

Unless we can detect the zoom level, this feature is dead in the water.

**Comment by austegard** [comment]
This seems to work rather well: https://github.com/yonran/detect-zoom
Demo: http://yonran.github.com/detect-zoom/test-page.html

**Comment by iangilman** [comment]
Sweet! Your google-fu is stronger than mine! I'll toss it in there.

**Comment by iangilman** [comment]
Seems like the thing to do is use that library directly (loading it as an additional JS file). Looks like it's licensed under BSD (see top of https://github.com/yonran/detect-zoom/blob/master/detect-zoom.js ), and we're MIT. That's fine, but we should update the license file to mention both. Sound fair?

**Comment by AppliedIS** [comment]
Fair.

--Oskar

-----Original Message-----

**Comment by iangilman** [comment]
At long last this is in! Looks pretty slick to me.

In the meantime, detect-zoom was changed to MIT license, so that simplifies things. I've also decided to include that code directly in bookmarklet.js, so we don't have to load an additional script.
